version: '3.8'

services:
  jenkins:
    image: jenkins
    ports: 
      - 8080:50000
    environment:
      - VIRTUAL_HOST:jenkins.kai-hude.de
      - VIRTUAL_PORT:8080
    volumes:
      jenkins_data:/var/jenkins_home

volumes:
  jenkins_data: {}